#!/bin/bash

set -e -u -o pipefail;

progdir=${0%/*};
progdir=${0%\\*};
progname=${0##*/};
progname=${progname##*\\};
progname=$(echo ${progname} | sed -e 's/-/ /;');

source "${progdir}/for-git-subcommands.sh";

optdelete="";

function usage() {
  returncode=${1:-0};

  cat << EOF >&2
Usage: ${progname} [-d]

-d     delete fully merged branch
-D     delete branch (even if not merged)
EOF

  exit ${returncode};
}

while getopts ":dDh" opt; do
  case "${opt}" in
    d)
      optdelete="-d";
      ;;
    D)
      optdelete="-D";
      ;;
    h)
      usage;
      ;;
    *)
      usage 1;
      ;;
  esac;
done;
shift $((OPTIND - 1));

if [ $# -ne 0 ]; then
  usage 1;
fi;

git branch \
  ${optdelete} \
  "temp/${branch_current}";
